spring:
  datasource:
    url: ${db.url:jdbc:postgresql://localhost:5433/postgres}
    username: ${db.username:postgres}
    password: ${db.password:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties.hibernate:
      show_sql: true
      format_sql: true
    hibernate:
      ddl-auto: validate
  mvc.format.date-time: iso
  liquibase:
    change-log: liquibase/db.changelog-master.yml